version: '3.7'

#
# Container names have a domain-like naming scheme to facilitate dnsmasq usage.
# By ending in .doc, which is not a valid TLD, we can easily configure dnsmasq
# to resolve these names to the docker machine. This allows the containers to
# use the same names to refer to each other as the host does when resolving the
# container names.
#

services:
  p4d.doc:
    build:
      context: containers/p4d
      args:
        # binding to the container IP address causes p4d to exit 255
        P4PORT: "0.0.0.0:1666"
        APT_URL: http://pkg-ondemand.bnr.perforce.com/perforce/r19.1/apt/ubuntu
        PUB_KEY: http://pkg-ondemand.bnr.perforce.com/perforce/r19.1/perforce.pubkey
    ports:
      - "1666:1666"
  ldap.doc:
    build:
      context: containers/ldap
    ports:
      - "389:389"
      - "636:636"
  idp.doc:
    build:
      context: containers/idp
      args:
        SVC_PROTOCOL: "https"
    environment:
      NODE_ENV: development
    ports:
      - "7000:7000"
  oidc.doc:
    build:
      context: containers/oidc
    environment:
      DEBUG: "oidc-provider:*"
      NODE_ENV: development
      PORT: 3001
      ISSUER: "http://oidc.doc:3001/"
      OIDC_CLIENT_ID: client_id
      OIDC_CLIENT_SECRET: client_secret
      OIDC_REDIRECT_URI: "https://svc.doc:3000/oidc/callback"
      OIDC_LOGOUT_REDIRECT_URI:  "https://svc.doc:3000"
    ports:
      - "3001:3001"
  svc.doc:
    build:
      context: .
      dockerfile: containers/svc/Dockerfile
    environment:
      NODE_ENV: development
      OIDC_CLIENT_ID: client_id
      OIDC_CLIENT_SECRET: client_secret
      OIDC_ISSUER_URI: "http://oidc.doc:3001/"
      DEBUG: "auth:*"
      # FORCE_AUTHN: "true"
      SVC_BASE_URI: "https://svc.doc:3000"
      DEFAULT_PROTOCOL: "oidc"
      CA_CERT_FILE: certs/ca.crt
      IDP_CERT_FILE: certs/server.crt
      IDP_KEY_FILE: certs/server.key
      SAML_IDP_SSO_URL: "http://idp.doc:7000/saml/sso"
      SAML_IDP_SLO_URL: "http://idp.doc:7000/saml/slo"
      SAML_SP_ISSUER: "urn:example:sp"
      # SAML_SP_AUDIENCE: captive-audience
      SP_CERT_FILE: certs/server.crt
      SP_KEY_FILE: certs/server.key
      # SP_KEY_ALGO: sha256
      LDAP_URL: "ldap://ldap.doc:389"
      LDAP_BIND_DN: "cn=admin,dc=example,dc=org"
      LDAP_BIND_CREDENTIALS: "admin"
      LDAP_SEARCH_BASE: "ou=users,dc=example,dc=org"
      LDAP_SEARCH_FILTER: "(uid={{username}})"
    ports:
      - "3000:3000"
