version: '3.7'

#
# Container names have a domain-like naming scheme to facilitate dnsmasq usage.
# By ending in .doc, which is not a valid TLD, we can easily configure dnsmasq
# to resolve these names to the docker machine. This allows the containers to
# use the same names to refer to each other as the host does when resolving the
# container names.
#

services:
  p4d.doc:
    build:
      context: containers/p4d
      args:
        # binding to the container IP address causes p4d to exit 255
        P4PORT: "0.0.0.0:1666"
        APT_URL: http://pkg-ondemand.bnr.perforce.com/perforce/main/apt/ubuntu
        PUB_KEY: http://pkg-ondemand.bnr.perforce.com/perforce/main/perforce.pubkey
    ports:
      - "1666:1666"
  idp.doc:
    build: containers/idp
    environment:
      NODE_ENV: development
    ports:
      - "7000:7000"
  oidc.doc:
    build:
      context: containers/oidc
    environment:
      NODE_ENV: development
      PORT: 3001
      ISSUER: "http://oidc.doc:3001/"
      OIDC_CLIENT_ID: client_id
      OIDC_CLIENT_SECRET: client_secret
      OIDC_REDIRECT_URI: "https://svc.doc:3000/oidc/callback"
    ports:
      - "3001:3001"
  svc.doc:
    build:
      context: .
      dockerfile: containers/svc/Dockerfile
    depends_on:
      - p4d.doc
      - oidc.doc
    environment:
      NODE_ENV: development
      OIDC_CLIENT_ID: client_id
      OIDC_CLIENT_SECRET: client_secret
      OIDC_ISSUER_URI: "http://oidc.doc:3001/"
      DEBUG: "oidc:*"
      # USE_HTTP: "true"
      OIDC_REDIRECT_URI: "https://svc.doc:3000/oidc/callback"
      SAML_SP_SSO_URL: "https://svc.doc:3000/saml/sso"
      SAML_SP_SLO_URL: "https://svc.doc:3000/saml/slo"
      SAML_IDP_SSO_URL: "http://idp.doc:7000/saml/sso"
      SAML_IDP_SLO_URL: "http://idp.doc:7000/saml/slo"
      SAML_SP_ISSUER: "urn:example:sp"
      # SAML_SP_AUDIENCE: captive-audience
      # SP_KEY_FILE: path/to/private.key
      # SP_KEY_ALGO: sha256
    ports:
      - "3000:3000"
